### ISSUE TITLE
Dependency "dictionary" failed validation.

### ISSUE THREAD

**Issue by robodude666** [vba-blocks/vba-blocks#11] opened 2018-08-29 03:56 UTC
When attempting to run `yarn build:addins` or `yarn build:win` I get the following error:

```
The downloaded file signature for dictionary@1.4.1 does not match the signature in the registry.
```

Using yarn v1.94 and node v8.9.4

**Comment by connerk** [comment] 2018-08-29 06:11
I confirm the same error. I bypassed by disabling the signature check after a bit of debugging

**Comment by robodude666** [comment] 2018-08-29 06:16
@connerk how did you do that?

**Comment by connerk** [comment] 2018-08-29 16:18
well, now I wish I took better notes... 
I can't reproduce the error now that it's fixed

but I'll help through it as best I can

VSCode debug settings in launch.json:
``` json
		{
			"type": "node",
			"request": "launch",
			"name": "Build:Addins",
                        "program": "${workspaceFolder}\\scripts\\build",
                        "cwd": "${workspaceFolder}\\addins"
		}
```



I started walking through code breaks in the `build()` function of ./lib/index.js (line 1885)

I think I traced it down to something in  `loadManifest()`  (line 739)

sorry I'm not more explicit... let me know if you get stuck somewhere.

**Comment by timhall** [comment] 2018-09-03 17:11
I'll need to tweak this when publish is worked out, but manually fixed the checksums to match S3. Should be fixed now.

**Closed by timhall** 2018-09-03 17:11 UTC
